# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://seanyboi.github.io/sorare_py/"

git_url = "https://github.com/seanyboi/sorare_py/tree/master/"

def custom_doc_links(name): return None
