# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LoginError": "00_login.ipynb",
         "LoginSorare": "00_login.ipynb"}

modules = ["login.py"]

doc_url = "https://seanyboi.github.io/sorarepy/"

git_url = "https://github.com/seanyboi/sorarepy/tree/master/"

def custom_doc_links(name): return None
